version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Rspec
          command: bundle exec rspec
